Minor code improvements and formatting

diff --git a/src/bin/statecraft b/src/bin/statecraft
--- a/src/bin/statecraft
+++ b/src/bin/statecraft
@@ -31,7 +31,7 @@ declare -r VERSION="1.0.2"
 declare -r BUILD="20251113"
 
 declare -r APP_NAME="$(basename "${BASH_SOURCE[0]}")"
-declare -r LIB_DIR="$(realpath "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/../lib/statecraft/" 2> /dev/null ||:)"
+declare -r LIB_DIR="$(realpath "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/../lib/statecraft/" 2>/dev/null ||:)"
 
 XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-}"
 [ -n "$XDG_RUNTIME_DIR" ] || { [ "$UID" == 0 ] && XDG_RUNTIME_DIR="/run" || XDG_RUNTIME_DIR="/run/user/$UID"; }
@@ -46,7 +46,7 @@ declare -r XDG_RUNTIME_DIR
 [ -x "$(type -p mountpoint)" ] || { echo "Missing script dependency: mountpoint" >&2; exit 1; }
 
 SELINUX=
-! selinuxenabled 2> /dev/null || SELINUX=y
+! selinuxenabled 2>/dev/null || SELINUX=y
 declare -r SELINUX
 
 # functions
@@ -77,7 +77,7 @@ ESCAPE=
 
 while [ $# -gt 0 ]; do
     if [[ "$1" =~ ^-[a-zA-Z0-9]{2,}$ ]]; then
-        set -- $(echo "${1:1}" | sed 's/./-& /g') "${@:2}"
+        set -- $(sed 's/./-& /g' <<<"${1:1}") "${@:2}"
         continue
     elif [[ "$1" =~ ^(--[a-zA-Z0-9_-]+)=(.*)$ ]]; then
         set -- "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}" "${@:2}"
@@ -201,7 +201,7 @@ else
     SCRIPTS_DIR="$LIB_DIR/paths.d"
 fi
 
-check_path "$SCRIPTS_DIR" "Invalid state script directory" -edrx
+check_path "$SCRIPTS_DIR" "Invalid state script directory" -edrxs
 
 # create random runtime directory
 RUN_DIR="$XDG_RUNTIME_DIR/statecraft"
@@ -231,19 +231,19 @@ fi
 __get_paths() {
     verbose + find "$SCRIPTS_DIR/" -name "*.state.sh"
 
-    local PATHS=()
+    local -a PATHS=()
     local SCRIPT= ID= DIR=
     for SCRIPT in "$SCRIPTS_DIR/"*".state.sh"; do
         ID="$(basename "$SCRIPT" ".state.sh")"
         [[ "$ID" =~ ^([a-zA-Z0-9:._-]|\\x[0-9a-f]{2})+(\+([a-zA-Z0-9:._-]|\\x[0-9a-f]{2})+)?$ ]] \
-            || { echo "Invalid path ${ID@Q}: Malformed state script filename" >&2; exit 1; }
+            || { echo "Invalid path ${ID@Q}: Malformed state script filename" >&2; return 1; }
 
-        SOURCE_DIR="$(unescape_path "${BASH_REMATCH[1]}" 2> /dev/null ||:)"
+        SOURCE_DIR="$(unescape_path "${BASH_REMATCH[1]}" 2>/dev/null ||:)"
         [ -n "$SOURCE_DIR" ] || { echo "Invalid path ${ID@Q}:" \
             "State script filename encodes no valid source path" >&2; return 1; }
 
         if [ -n "${BASH_REMATCH[3]}" ]; then
-            TARGET_DIR="$(unescape_path "${BASH_REMATCH[3]}" 2> /dev/null ||:)"
+            TARGET_DIR="$(unescape_path "${BASH_REMATCH[3]}" 2>/dev/null ||:)"
             [ -n "$TARGET_DIR" ] || { echo "Invalid path ${ID@Q}:" \
                 "State script filename encodes no valid target path" >&2; return 1; }
         fi
@@ -259,6 +259,8 @@ __get_paths() {
 
 PATHS=()
 readarray -t PATHS < <(__get_paths)
+[ "${#PATHS[@]}" -gt 0 ] || exit 1
+
 declare -r PATHS
 
 # run state scripts
@@ -301,7 +303,7 @@ __EXIT=0
     cmd cd "$TARGET_DIR"
     verbose + "$(type -p "${COMMAND[0]}")" "${COMMAND[@]:1}"
     exec "$(type -p "${COMMAND[0]}")" "${COMMAND[@]:1}"
-) || { __EXIT=$?; true; }
+) || { __EXIT=$?; :; }
 __RUNNING=
 
 exit $__EXIT
